/* Generated by build.mjs. Do not edit; edit src/diagnostic.mjs and rebuild. */
(function () {
  var form = document.querySelector('[data-assessment]');
  if (!form) return;

  var hidden = document.querySelectorAll('.js-only');
  for (var h = 0; h < hidden.length; h++) hidden[h].classList.remove('js-only');

  var panel = document.querySelector('[data-result]');
  var target = document.querySelector('[data-result-body]');
  var progress = document.querySelector('[data-progress]');
  var TOTAL = 6;

  function verdictFor(a) {
    if (a.identity !== 'clean') return 'identity-drift';
    if (a.definition !== 'clean' || a.count !== 'clean' || a.height === 'low' || a.height === 'mid') {
      return 'definitional-drift';
    }
    if (a.retrieval === 'person') return 'retrieval-gap';
    return 'pass';
  }

  function collect() {
    var picked = form.querySelectorAll('input[type=radio]:checked');
    var a = {};
    for (var i = 0; i < picked.length; i++) a[picked[i].getAttribute('data-q')] = picked[i].value;
    return a;
  }

  function lift(id) {
    var src = document.getElementById(id);
    if (!src) return null;
    var node = src.cloneNode(true);
    node.removeAttribute('id');
    node.className = '';
    return node;
  }

  function render() {
    var a = collect();
    var n = 0;
    for (var k in a) if (Object.prototype.hasOwnProperty.call(a, k)) n++;

    if (n < TOTAL) {
      panel.hidden = true;
      progress.textContent = n === 0 ? '' : n + ' of ' + TOTAL + ' answered.';
      return;
    }

    progress.textContent = '';
    while (target.firstChild) target.removeChild(target.firstChild);

    var main = lift('verdict-' + verdictFor(a));
    if (main) target.appendChild(main);

    if (a.disagreement === 'seniority' || a.disagreement === 'dropped') {
      var note = lift('verdict-authority');
      if (note) target.appendChild(note);
    }

    panel.hidden = false;
  }

  form.addEventListener('change', render);
  render();
}());
